version: 2
defaults: &defaults
    docker:
      - image: docker:17.11.0-ce-git
install_dependency: &install_dependency
          name: Installation of build and deployment dependencies.
          command: |
            apk update
            apk add --no-cache bash curl
            apk upgrade
            apk add --no-cache jq py-pip sudo
            sudo pip install awscli --upgrade
            sudo pip install docker-compose
            
install_deploysuite: &install_deploysuite
          name: Installation of install_deploysuite.
          command: |
            git clone --branch v1.3 https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
            cp ./../buildscript/master_deploy.sh .
            cp ./../buildscript/buildenv.sh .
            cp ./../buildscript/awsconfiguration.sh .

restore_cache_settings_for_build: &restore_cache_settings_for_build
  key: docker-node-modules-lsp-{{ checksum "package-lock.json" }}

save_cache_settings: &save_cache_settings
  key: docker-node-modules-lsp-{{ checksum "package-lock.json" }}
  paths:
    - node_modules

jobs:
  # Build & Deploy against development backend
  "build-dev":
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: *install_dependency
      - run: *install_deploysuite
      - restore_cache: *restore_cache_settings_for_build
      - run: 
          name: "configuring environment"
          command: |
            ./awsconfiguration.sh DEV
            ./buildenv.sh -e DEV -b dev-legacymmapp-buildvar            
      - run: 
          name: Building software
          command: |
            source buildenvvar
            ./build.sh DEV      
      - save_cache: *save_cache_settings
      - deploy:
          command: |
            source awsenvconf
            ./buildenv.sh -e DEV -b dev-legacymmapp-deployvar
            source buildenvvar
            ./master_deploy.sh -d ECS -e DEV -t $CIRCLE_SHA1 -s dev-legacymmapp-appvar
 
  # Build & Deploy against production backend
  "build-prod":
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: *install_dependency
      - run: *install_deploysuite
      - restore_cache: *restore_cache_settings_for_build
      - run: 
          name: "configuring environment"
          command: |
            ./awsconfiguration.sh PROD
            ./buildenv.sh -e PROD -b prod-legacymmapp-buildvar            
      - run: 
          name: Building software
          command: |
            source buildenvvar
            ./build.sh PROD 
      - save_cache: *save_cache_settings
      - deploy:
          command: |
            source awsenvconf
            ./buildenv.sh -e PROD -b dev-legacymmapp-deployvar
            source buildenvvar
            ./master_deploy.sh -d ECS -e RPOD -t $CIRCLE_SHA1 -s dev-legacymmapp-appvar

workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "develop" branch only.
      - "build-dev":
          context : org-global
          filters:
            branches:
              only:
                - develop

      # Production builds are exectuted only on tagged commits to the
      # master branch.
      - "build-prod":
          context : org-global
          filters:
            branches:
              only: master
